import { constants } from "node:fs";
import { access, copyFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const source = resolve(__dirname, "../../database/src/generated/prisma/client.ts");
const target = resolve(__dirname, "../src/prisma-generated/client.ts");

async function sync(): Promise<void> {
  await mkdir(resolve(__dirname, "../src/prisma-generated"), { recursive: true });

  try {
    await access(source, constants.F_OK);
    await copyFile(source, target);
  } catch {
    await writeFile(
      target,
      "// Prisma client types are generated by `npm run db:generate`.\nexport type PrismaClientPlaceholder = never;\n"
    );
  }
}

await sync();
